services:
  app:
    build: ./app
    container_name: front-end
    volumes:
      - ./app/src:/appcode
    ports:
      - 8501:8501
    networks:
      - pollpal_app-network

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes:
      - ./api:/apicode
      - ./app/src/pages/model_files:/model_files
    ports:
      - 4000:4000
    networks:
      - pollpal_app-network

  db:
    env_file:
      - ./api/.env
    image: mysql:8
    container_name: mysql_db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306
    restart: unless-stopped
    networks:
      - pollpal_app-network

networks:
  pollpal_app-network:
    driver: bridge
